# Generated by Django 4.2.3 on 2023-08-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0002_remove_coviddata_date_checked_remove_coviddata_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='death',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='hospitalized',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='hospitalized_cumulative',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='hospitalized_currently',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='in_icu_cumulative',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='in_icu_currently',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='negative',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='on_ventilator_cumulative',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='on_ventilator_currently',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='pending',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='positive',
            field=models.IntegerField(null=True),
        ),
    ]
