# Generated by Django 4.2.3 on 2023-08-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0003_alter_coviddata_death_alter_coviddata_hospitalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='death_increase',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='hospitalized_increase',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='pos_neg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='states',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='total_test_results',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='total_test_results_increase',
            field=models.IntegerField(null=True),
        ),
    ]
