# Generated by Django 4.2.3 on 2023-08-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0004_alter_coviddata_death_increase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddata',
            name='death_increase',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='hospitalized_cumulative',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='hospitalized_currently',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='hospitalized_increase',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='in_icu_cumulative',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='in_icu_currently',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='negative_increase',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='on_ventilator_cumulative',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='on_ventilator_currently',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='pos_neg',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='positive_increase',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='recovered',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='states',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='total',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='total_test_results',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='total_test_results_increase',
        ),
    ]
